export const ICONS = {
  ADD: '⨁',
  ARROW_DOWN: '↓',
  ARROW_RIGHT: '→',
  BLOCK: '█',
  CANCEL: 'ⓧ',
  CHECKMARK_GREEN: '✅',
  CHEVRON_LEFT: '‹',
  CHEVRON_RIGHT: '›',
  ELLIPSIS: '…',
  FOLDER: '📁',
  HEART: '❤️',
  MAGNIFYING_GLASS: '🔍',
  OPEN_EXTERNAL: ' ↗',
  PAPERCLIP: '📎',
  PENCIL: '✐',
  STAR: '✭',
  VERTICAL_ELLIPSIS: '⋮',
};
